# Generated by Django 3.1.1 on 2020-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_auto_20200919_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score_int',
            field=models.IntegerField(default=1, verbose_name='score'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
