# Generated by Django 3.1.1 on 2020-09-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0003_auto_20200919_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Opinion',
        ),
    ]
